stfc/cloud-deployed-apps

application.yaml, guestbook/application.yaml, rabbit-exporter/application.yaml, rabbit-exporter/values.yaml
And guestbook&rabbit-exporter yaml files
Created folder structure for using appofapps
=> Created appofapps application.yaml

prod-values/harbor-values.yaml
Related issue: https://stfc.atlassian.net/jira/software/c/projects/CLDSCRM/boards/77?selectedIssue=CLDSCRM-591
Changes:
Changed config to use S3 instead of Swift, as future versions of Harbor (3.0+) will start to move away from supporting Swift (see: https://github.com/goharbor/harbor/issues/19317)
Commented out configuration left in for when it comes to performance testing.
=> Update harbor-values.yaml to use S3

clusters/staging-management-cluster/app-values.yaml
Now that the PR has been merged, we need to point our staging cluster back to main for good
=> MAINT: Repoint to main

clusters/akhil-harbor-test/overrides/infra/deployment.yaml, clusters/staging-management-cluster/infra-values.yaml
Working on adding harbor to argocd, need this cluster for test.
=> ENH: Adding a harbor test cluster

clusters/staging-management-cluster/infra-values.yaml
Changed target revision to main from multi-cluster
=> BUG: Changed target revision to main

clusters/anish-monitoring-test/overrides/deployment.yaml, clusters/staging-management-cluster/infra-values.yaml
cluster to test development of monitoring config using capi-addons
=> ENH: Adding cluster for setting up monitoring

charts/apps/longhorn/Chart.yaml, charts/apps/longhorn/values.yaml, charts/argocd-apps/values.yaml, clusters/akhil-harbor-test/app-values.yaml, clusters/akhil-harbor-test/argocd-values.yaml, clusters/akhil-harbor-test/overrides/apps/longhorn-values.yaml, clusters/akhil-harbor-test/overrides/infra/deployment.yaml, docs/DEPLOYING_APPS.md
add longhorn as a managed app for argocd 
add config to setup cluster `akhil-harbor-test` as a test cluster for longhorn
=> ENH: add longhorn managed application

clusters/david-harbor-test/overrides/infra/deployment.yaml
This allows us to test ingress, now that the service is up and managed with ArgoCD in its prototype phase
---
Have you:
---
Have you:
=> MAINT: Switch the FIP for to test.harbor.stfc.ac.uk

charts/argocd-apps/templates/cloud-deployed-apps.yaml, charts/argocd-infra/templates/cloud-deployed-infra.yaml
latest change to account for prod SHA broke staging - this is an attempt to fix the bug
=> BUG: fix issue where cloudDeployedApps undefined

clusters/staging-management-cluster/overrides/infra/deployment.yaml
this one has domain changes setup for *.staging.nubes.stfc.ac.uk
Also testing whether argo-cd can handle an IP change like this without manual intervention
=> move ip for staging mgmt ingress

clusters/prod-mgmt/app-values.yaml, clusters/prod-mgmt/infra-values.yaml, clusters/victoria-metrics-prod/app-values.yaml
point prod clusters to a commit sha
---
Have you:
---
Have you:
=> MAINT: point prod clusters to a commit sha

clusters/jupyter-training/overrides/infra/deployment.yaml
enable kube-prom-stack addons and emailing for jupyter
=> ENH: enable kube-prom-stack logs for JHub cluster

clusters/prod-worker/app-values.yaml, clusters/prod-worker/argocd-values.yaml, clusters/prod-worker/overrides/infra/deployment.yaml
just manage infra for now - apps to follow
=> DEPLOY: Add prod-worker cluster

docs/DEPLOYING_CLUSTER.md
Some updates for how to deploy an ArgoCD cluster from scratch.
---
Have you:
---
Have you:
=> Updates for deploying Argo on a cluster

clusters/test-capi-addons-2/app-values.yaml, clusters/test-capi-addons-2/argocd-values.yaml, clusters/test-capi-addons-2/infra-values.yaml, clusters/test-capi-addons-2/overrides/infra/deployment.yaml
Test ArgoCD deployment in prod
---
Have you:
---
Have you:
=> DEPLOY: Test deployment for argocd

clusters/test-capi-addons-2/overrides/infra/deployment.yaml
Update floating IP
---
Have you:
---
Have you:
=> Update floating IP

charts/dev/argocd/values.yaml, docs/secrets.md, secrets/dev/.sops.yaml, secrets/dev/management-app-creds.yaml, secrets/dev/management-fip.yaml
Adds secret handling into ArgoCD using helm secrets, and adds some initial secrets for dev pointing to a scratch space to prove the concept
---
Have you:
---
Have you:
=> ENH: Add secret handling and secrets for dev

charts/dev/argocd/values.yaml, charts/dev/capi-infra/values.yaml, clusters/david-dev/management/apps.yaml, clusters/david-dev/management/argocd-setup-values.yaml, clusters/david-dev/management/infra-values.yaml, clusters/dev/management/apps.yaml, secrets/david-dev/management/.sops.yaml, secrets/david-dev/management/api-server-fip.yaml, secrets/david-dev/management/app-creds.yaml
Fixes the secret handling with Argo:
- Fix up the path
- Add another cluster for testing this
- Change Argo Config Map to correctly handle the protocol and set appropriate security policy 
---
Have you:
---
Have you:
=> Fix secrets argo

docs/charts.md, scripts/deploy.sh, secrets/dev/worker/api-server-fip.yaml, secrets/dev/worker/app-creds.yaml
put values under subchart for worker
=> BUG: fix dev secrets

clusters/dev/test-jupyter/infra-values.yaml, secrets/dev/test-jupyter/.sops.yaml, secrets/dev/test-jupyter/api-server-fip.yaml, secrets/dev/test-jupyter/app-creds.yaml
Adds a development cluster for JupyterHub so we can continue to port the chart in
---
Have you:
---
Have you:
=> DEPLOY: Add a dev cluster for Jupyterhub

clusters/dev/david-jhub/infra-values.yaml, secrets/dev/david-jhub/.sops.yaml, secrets/dev/david-jhub/api-server-fip.yaml, secrets/dev/david-jhub/app-creds.yaml
Adds another testing cluster, whilst we leave the other JHub one parked pending some diagnostics about Calico
---
Have you:
---
Have you:
=> DEPLOY: Add a david-test cluster

charts/staging/argocd/Chart.yaml, charts/staging/argocd/requirements.yaml, charts/staging/argocd/values.yaml, charts/staging/capi-infra/Chart.yaml, charts/staging/capi-infra/requirements.yaml, charts/staging/capi-infra/values.yaml, charts/staging/cert-manager/Chart.yaml, charts/staging/cert-manager/requirements.yaml, charts/staging/cert-manager/templates/le-prod-clusterissuer.yaml, charts/staging/cert-manager/templates/le-staging-clusterissuer.yaml, charts/staging/cert-manager/templates/self-signed-clusterissuer.yaml, charts/staging/cert-manager/values.yaml, charts/staging/cluster-api-addon-provider/Chart.yaml, charts/staging/cluster-api-addon-provider/requirements.yaml, charts/staging/longhorn/Chart.yaml, charts/staging/longhorn/requirements.yaml, charts/staging/longhorn/values.yaml
Add charts for staging environment - promoted from dev 
---
Have you:
---
Have you:
=> Add staging charts

clusters/staging/management/apps.yaml, clusters/staging/management/argocd-setup-values.yaml, clusters/staging/management/infra-values.yaml, secrets/staging/management/.sops.yaml, secrets/staging/management/api-server-fip.yaml, secrets/staging/management/app-creds.yaml
This sets up a staging environment for ArgoCD with a management cluster.
---
Have you:
---
Have you:
=> Add a staging environment

secrets/staging/management/.sops.yaml, secrets/staging/management/api-server-fip.yaml, secrets/staging/management/app-creds.yaml
Rotates the key for staging management, pending a re-deployment
---
Have you:
---
Have you:
=> Rotate key for staging mgmt

clusters/staging/management/argocd-setup-values.yaml, clusters/staging/management/infra-values.yaml
- Add an indent so we actually get ingress deployed
- Add the DNS record for ArgoCD
---
Have you:
---
Have you:
=> Set staging DNS details

clusters/dev/management/apps.yaml, clusters/dev/management/infra-values.yaml, clusters/dev/worker/infra-values.yaml, secrets/dev/management/.sops.yaml, secrets/dev/management/api-server-fip.yaml, secrets/dev/management/app-creds.yaml, secrets/dev/worker/.sops.yaml, secrets/dev/worker/api-server-fip.yaml, secrets/dev/worker/app-creds.yaml
remaking cluster so rotating argo age key
=> MAINT: rotate out dev-argo age key

docs/app-setup.md, docs/charts.md, docs/child-clusters.md, docs/clusters.md, docs/deploying-apps.md, docs/folder-based-flow.md, docs/infra-setup.md, docs/secrets.md
a few fixes for our docs - just formatting fixes, wording changes and tagging code blocks with `bash` or `yaml` as appropriate
=> DOC: small fixes for our docs

secrets/dev/management/app-creds.yaml, secrets/dev/worker/app-creds.yaml
use app-cred generated from svc-preprod-k8s service account
=> MAINT: rotate app cred

secrets/dev/management/api-server-fip.yaml, secrets/dev/management/app-creds.yaml, secrets/dev/worker/api-server-fip.yaml, secrets/dev/worker/app-creds.yaml
update sops files with updated keys
=> BUG: update sops files with new keys

charts/dev/cluster-api-addon-provider/requirements.yaml
going to test upgrading capi addons on dev cluster
=> Bump capi addons to 0.5.9

charts/dev/capi-infra/requirements.yaml, charts/dev/cluster-api-addon-provider/requirements.yaml
=> switch charts to use azimuth-cloud repo

clusters/dev/management/apps.yaml, docs/clusters.md
add a prefix for dev clusters so it matches what we do with staging cluster
=> prefix dev onto dev clusters

clusters/dev/management/apps.yaml
remove this line to remove name mismatch between desired cluster name and helm release
=> BUG: name mismatch due to release name

clusters/dev/galaxy/apps.yaml, clusters/dev/galaxy/argocd-setup-values.yaml, clusters/dev/galaxy/infra-values.yaml, clusters/dev/galaxy/materials-galaxy-values.yaml, secrets/dev/galaxy/.sops.yaml, secrets/dev/galaxy/api-server-fip.yaml, secrets/dev/galaxy/app-creds.yaml, secrets/dev/management/app-creds.yaml, secrets/dev/worker/app-creds.yaml
add cluster to deploy dev galaxy
also fix a yaml formatting bug for dev mgmt and worker clusters app-cred secrets
=> DEPLOY: add new dev galaxy cluster

secrets/dev/galaxy/app-creds.yaml
rotate galaxy app-cred since the other one expired
=> rotate galaxy cluster creds

charts/dev/materials-galaxy/values.yaml, clusters/dev/galaxy/materials-galaxy-values.yaml
going to use csi cinder as storage medium for now as longhorn is having issues
some small fixes http - https
=> some more galaxy fixes

charts/dev/manila/Chart.yaml, charts/dev/manila/requirements.yaml, charts/dev/manila/templates/manila-sc.yaml, charts/dev/manila/values.yaml
allows us to manage manila storage
TODO: figure out best method to create secret for manila
TODO: figure out best method to set manila as default storage class or not
=> Add manila storage chart

charts/dev/materials-galaxy/requirements.yaml, charts/dev/materials-galaxy/templates/nginx-configmap.yaml, charts/dev/materials-galaxy/values.yaml, clusters/dev/galaxy/apps.yaml, clusters/dev/galaxy/argocd-setup-values.yaml, clusters/dev/galaxy/materials-galaxy-values.yaml, scripts/deploy.sh
a set of fixes to productionize galaxy - and get it working on argo
=> BUG: galaxy cluster fixes

charts/dev/capi-infra/values.yaml
to test pr - https://github.com/stfc/cloud-capi-values/pull/28
=> TST: calico cni fixes test

charts/dev/capi-infra/values.yaml
looks like we don't need this - pr was closed
=> Revert "TST: calico cni fixes test"

charts/dev/materials-galaxy/values.yaml, clusters/dev/galaxy/apps.yaml
remove redundant values (which are set upstream)
remove duplicate ignorediff in apps.yaml
=> MAINT: small fixes for galaxy

charts/dev/capi-infra/values.yaml
update capi image on dev to test
=> update capi image to 1.28.12

charts/dev/capi-infra/values.yaml, clusters/dev/galaxy/infra-values.yaml
issue with dev openstack  reverting
=> BUG: revert capi image back to 1.28.7

charts/dev/capi-infra/requirements.yaml, charts/dev/cluster-api-addon-provider/requirements.yaml
=> Update CAPI charts 0.10.0, 0.6.1

charts/dev/capi-infra/requirements.yaml
Update dev capi-helm-charts from version 0.10.0 to 0.10.1
=> Update chart version

charts/staging/capi-infra/requirements.yaml, charts/staging/capi-infra/values.yaml, charts/staging/cert-manager/values.yaml, charts/staging/cluster-api-addon-provider/requirements.yaml
Promote capi infra, capi addon provider and cert manager charts to staging
=> Promote capi infra, capi addon provider and cert manager charts to staging

clusters/staging/management/infra-values.yaml
Add kubePrometheusStack config
=> Enable staging monitoring

charts/dev/capi-infra/values.yaml
set smtp_from as cloud-support email
=> BUG: add emailing alert "send from"

secrets/dev/smtp-smarthost.yaml
since we're actually sending alerts for the management  cluster - we should set the smtp smarthost properly
=> BUG: set smtp smarthost

charts/prod/capi-infra/requirements.yaml, charts/prod/capi-infra/values.yaml, charts/prod/cert-manager/values.yaml, charts/prod/cluster-api-addon-provider/requirements.yaml
Promote capi infra, capi addon provider and cert manager charts to prod
=> Promote capi infra, capi addon provider and cert manager charts to prod

charts/staging/capi-infra/values.yaml, clusters/staging/management/infra-values.yaml, clusters/staging/worker/infra-values.yaml, secrets/staging/.sops.yaml, secrets/staging/smtp-smarthost.yaml
dev monitoring stack is setup for management so promote the changes onto staging
=> Promote monitoring changes from dev to staging

clusters/prod/management/apps.yaml, clusters/prod/management/infra-values.yaml, clusters/prod/worker/infra-values.yaml, secrets/prod/.sops.yaml, secrets/prod/smtp-smarthost.yaml
=> Promote monitoring changes from staging to prod

charts/prod/capi-infra/values.yaml
missed this setting - copied out-dated staging values
=> BUG: promote chart changes from staging to prod

clusters/dev/worker/infra-values.yaml
need to do this to debug our K8s image issues
=> BUG: attempt to change CAPI image version

secrets/dev/.sops.yaml, secrets/dev/smtp-smarthost.yaml
=> BUG: re-add smtp-smarthost secret

clusters/dev/vicmet/apps.yaml
=> Fix apiversion

charts/dev/argocd/Chart.yaml, charts/dev/cert-manager/Chart.yaml, charts/dev/longhorn/Chart.yaml, charts/dev/manila-csi/Chart.yaml, charts/dev/materials-galaxy/Chart.yaml
update chart versions for all charts we're managing on dev
=> Bump up chart versions for dev

secrets/dev/vicmet/app-creds.yaml
=> Rotate app-creds for prod

clusters/dev/vicmet/infra-values.yaml, secrets/dev/vicmet/api-server-fip.yaml
=> Change FIPs to prod FIPs

charts/prod/capi-infra/values.yaml
Make prod capi-infra chart values the same as staging including formatting. Add missing smtp_from field
=> BUG: prod alertmanager config missing cloud smtp_from

clusters/dev/vicmet/infra-values.yaml
=> Change FIP for VM dev cluster

charts/dev/victoria-metrics/values.yaml
Add lines to choose nginx ingress class
Have you:
=> Minor changes to vicmet values

docs/apps/storage.md
=> [MAINT] Update storage.md

secrets/dev/davew/app-creds.yaml
Added missing openstack-cluster to app creds
=> Argo test cluster

charts/dev/opensearch/Chart.yaml, charts/dev/opensearch/secret-templates/opensearch.yaml, charts/dev/opensearch/templates/admin-secret.yaml, charts/dev/opensearch/templates/opensearch-cluster.yaml, charts/dev/opensearch/templates/opensearch-dashboards-ingress.yaml, charts/dev/opensearch/templates/opensearch-nodes-ingress.yaml, charts/dev/opensearch/templates/security-config-secret.yaml, charts/dev/opensearch/values.yaml, docs/apps/opensearch.md
Add opensearch chart to dev. This uses opensearch-k8s-operator. 
This also allows iris-iam config setup
=> MAINT: add Opensearch

charts/dev/capi-infra/Chart.yaml, charts/dev/cluster-api-addon-provider/Chart.yaml
test latest chart changes to capi-helm-charts. Upstream has not yet released a new chart - so test with a custom dev chart
=> TST: use dev capi-helm-chart

charts/dev/capi-infra/Chart.yaml
Use new capi-helm-chart release and azimuth-cloud chart repo
>**Note:** This needs testing
---
Have you:
---
Have you:
=> MAINT: Update chart repo and version

secrets/prod/.sops.yaml, secrets/prod/smtp-smarthost.yaml, secrets/prod/worker/.sops.yaml, secrets/prod/worker/api-server-fip.yaml, secrets/prod/worker/app-creds.yaml
Rotate smtp smart host file and worker secrets
Rebuilding the prod clusters
Rebuilding the prod cluster after deletion
---
Have you:
---
Have you:
=> Rotate prod secrets

charts/dev/capi-infra/Chart.yaml, charts/dev/cluster-api-addon-provider/Chart.yaml
This grabs the latest versions for dev with a view to upgrading staging and prod with the latest versions
---
Have you:
---
Have you:
=> Bump infra values for CAPI infra

charts/dev/capi-infra/values.yaml, charts/prod/capi-infra/Chart.yaml, charts/prod/capi-infra/values.yaml, charts/prod/cluster-api-addon-provider/Chart.yaml, charts/staging/capi-infra/values.yaml, clusters/prod/management/infra-values.yaml, clusters/prod/worker/infra-values.yaml
We have promoted this through dev and staging where it has worked correctly. Promote a final time to prod
---
Have you:
---
Have you:
=> Promote latest CAPI infra to prod

.github/workflows/pr_check_copies.sh, .github/workflows/pr_copied_files.yaml
The included workflow file will find any changes made under the Charts folder for the staging and prod environments.
It will then pass each of these to the bash script for comparison and return whether they match with the previous environment(s).
Please have a look over and give any thoughts on the process, code etc.
=> New workflow to detect whether files within charts directory match

charts/prod/capi-infra/Chart.yaml, charts/prod/capi-infra/values.yaml
Moving the files from staging to prod in prep for bumping to next version.
=> MAINT: Moving Capi chart and values yaml from Staging to Prod

charts/dev/capi-infra/Chart.yaml, charts/dev/capi-infra/values.yaml
Getting the image ready to go through staging and to prod.
=> MAINT: Bumping the Capi version in Dev to 1.30.6

clusters/dev/worker/apps.yaml
missing line to use secrets for setting up galaxy
=> BUG: add line pointing to secrets file for galaxy

charts/staging/capi-infra/Chart.yaml, charts/staging/capi-infra/values.yaml
Bumping the Capi image version in staging to 1.30.6
=> Bumping the Capi version in staging to 1.30.6

charts/prod/capi-infra/Chart.yaml, charts/prod/capi-infra/values.yaml
=> MAINT: Bumping the Capi version in Prod to 1.30.6

clusters/dev/management/argocd-setup-values.yaml, clusters/dev/management/infra-values.yaml, clusters/dev/worker/infra-values.yaml
dev domain names don't match staging/prod - change to match
=> MAINT: standardise domain names

clusters/staging/worker/argocd-setup-values.yaml
fix longhorn values for staging-worker cluster - wrong indentation
=> BUG: wrong indentation

secrets/dev/_shared/infra/.sops.yaml, secrets/dev/_shared/infra/smtp-smarthost.yaml, secrets/dev/management/infra/.sops.yaml, secrets/dev/management/infra/api-server-fip.yaml, secrets/dev/management/infra/app-creds.yaml, secrets/dev/rwhiting/infra/.sops.yaml, secrets/dev/rwhiting/infra/api-server-fip.yaml, secrets/dev/rwhiting/infra/app-creds.yaml, secrets/dev/vicmet/infra/.sops.yaml, secrets/dev/vicmet/infra/api-server-fip.yaml, secrets/dev/vicmet/infra/app-creds.yaml, secrets/dev/worker/apps/.sops.yaml, secrets/dev/worker/apps/materials-galaxy.yaml, secrets/dev/worker/infra/.sops.yaml, secrets/dev/worker/infra/api-server-fip.yaml, secrets/dev/worker/infra/app-creds.yaml
add kalibh's dev key to access/create sops secrets
it's a case of adding his age key to all dev `.sops.yaml` and running sops updatekeys on each directory - using script `update-keys.sh dev <clustername>`
=> MAINT: add kalibh's key to dev

clusters/dev/cloud-chatops/infra-values.yaml, secrets/dev/cloud-chatops/infra/.sops.yaml, secrets/dev/cloud-chatops/infra/api-server-fip.yaml, secrets/dev/cloud-chatops/infra/app-creds.yaml
Deploy a new cluster for chatops to make it easier for development changes
---
Have you:
---
Have you:
=> ENH: Add new cluster for cloud chatops

charts/dev/chatops/Chart.yaml, charts/dev/chatops/templates/cloud-chatops.yaml, charts/dev/chatops/templates/config-map.yaml, charts/dev/chatops/values.yaml
Update to version 5 of the chatops image. This gives us access to the `/find-host` comand. For this we need to add the node IP to the environment variables and add the pull requests channel to the config.
---
Have you:
---
Have you:
=> Update to v5

clusters/dev/harbor/infra-values.yaml, secrets/dev/harbor/infra/.sops.yaml, secrets/dev/harbor/infra/api-server-fip.yaml, secrets/dev/harbor/infra/app-creds.yaml
Deploy a cluster to test harbor instance
---
Have you:
---
Have you:
=> DEPLOY: Added test harbor cluster

clusters/dev/harbor/infra-values.yaml
=> Add ingress for harbor cluster

charts/dev/capi-infra/values.yaml, clusters/dev/worker/infra-values.yaml
fix various bugs with our alertmanager setup - mostly around fixing go templates for email messages and tweaking send rate  
---
Have you:
---
Have you:
=> BUG: Alertmanager fixes

secrets/dev/_shared/infra/.sops.yaml, secrets/dev/_shared/infra/smtp-smarthost.yaml, secrets/dev/cloud-chatops/infra/.sops.yaml, secrets/dev/cloud-chatops/infra/api-server-fip.yaml, secrets/dev/cloud-chatops/infra/app-creds.yaml, secrets/dev/management/infra/.sops.yaml, secrets/dev/management/infra/api-server-fip.yaml, secrets/dev/management/infra/app-creds.yaml, secrets/dev/rwhiting/infra/.sops.yaml, secrets/dev/rwhiting/infra/api-server-fip.yaml, secrets/dev/rwhiting/infra/app-creds.yaml, secrets/dev/vicmet/infra/.sops.yaml, secrets/dev/vicmet/infra/api-server-fip.yaml, secrets/dev/vicmet/infra/app-creds.yaml, secrets/dev/worker/apps/.sops.yaml, secrets/dev/worker/apps/chatops.yaml, secrets/dev/worker/apps/materials-galaxy.yaml, secrets/dev/worker/apps/opensearch.yaml, secrets/dev/worker/infra/.sops.yaml, secrets/dev/worker/infra/api-server-fip.yaml, secrets/dev/worker/infra/app-creds.yaml
add key so that Aziz can decrypt secrets for dev and review changes
=> add aziz age key to dev environment

charts/dev/capi-infra/Chart.yaml, charts/staging/capi-infra/Chart.yaml, charts/staging/capi-infra/values.yaml
test alertmanager changes on staging
=> DEPLOY: promote alertmanager fixes to staging

charts/dev/chatops/values.yaml
Adding openstack query library to list of repos
Have you:
---
Have you:
=> ENH: Add repo to list

charts/dev/capi-infra/values.yaml
=> remake capi k8s image

secrets/dev/vicmet/infra/app-creds.yaml
Old app creds expired
---
Have you:
---
Have you:
=> [Deployment] Rotate app cred for vicmet cluster

secrets/dev/cloud-chatops/infra/app-creds.yaml
Application credentials were deleted from OpenStack so need to be renewed
Have you:
---
Have you:
=> MAINT: Renew cluster application credentials

secrets/staging/worker/apps/chatops.yaml
Re-generated a new token from the STFC-Cloud GitHub account
Have you:
---
Have you:
=> MAINT: Rotate GitHub PAT token to Cloud account

charts/dev/capi-infra/values.yaml
dev now has the latest capi images
=> bump to latest capi image on dev

charts/prod/capi-infra/Chart.yaml, charts/prod/capi-infra/values.yaml
bump capi to 0.12.2
bump capi addons to 0.7.1
fix alertmanager config
fix capi rollout config to not remove nodes before they are fully drained
=> promote capi changes to prod

charts/prod/rabbit-consumer/Chart.yaml
set proper chart name for rabbit-consumer chart
=> typo: set proper chart names

charts/dev/capi-infra/Chart.yaml, clusters/dev/_shared/monitoring.yaml
update to using new chart version 1.4.1
fix bug with monitoring
=> tweak dev config

clusters/dev/worker/apps.yaml
update dev app paths to match new location
=> update secrets path

charts/prod/rabbit-consumer/Chart.yaml, clusters/prod/worker/rabbit-consumer-values.yaml
=> Point consumer at alpha chart

charts/dev/rabbit-consumer/Chart.yaml, clusters/prod/worker/rabbit-consumer-values.yaml
To consume both the ral.info and ral.error messages
---
Have you:
---
Have you:
=> Testing rabbit consumer queues with separate queues

charts/prod/rabbit-consumer/Chart.yaml
=> Point prod to alpha consumer chart

charts/prod/rabbit-consumer/Chart.yaml
=> Point consumers to new alpha chart

.github/workflows/pr_copied_files.yaml
v46 patches changed files issue
=> re-add changed-files action

clusters/dev/worker/apps.yaml
issue with postgresql label being too big solved with argocd serversideapply=true
=> fix issue with galaxy

secrets/staging/worker/apps/harbor.yaml
=> update harbor secrets

clusters/staging/worker/harbor-values.yaml
This is the host for the Harbor dev database
---
Have you:
---
Have you:
=> Change database host

clusters/dev/worker/apps.yaml
issue commented here: https://github.com/argoproj/argo-cd/issues/6401#issuecomment-854995249
tested and works
=> ignorediff on longhorn crds

clusters/_shared/alerting.yaml, clusters/_shared/monitoring.yaml, clusters/dev/management/secrets/infra/api-server-fip.yaml, clusters/dev/management/secrets/infra/app-creds.yaml
- add missing key "addon"
- rotate dev management secrets - they weren't working - need to investigate what caused this
=> bug: fix bug with shared monitoring values

clusters/staging/worker/apps.yaml
issue commented here: https://github.com/argoproj/argo-cd/issues/6401#issuecomment-854995249
=> bug: promote out-of-sync longhorn issue fix to staging

clusters/staging/worker/secrets/apps/harbor.yaml
Define config for storage backend
---
Have you:
---
Have you:
=> Add imageChartStorage

clusters/staging/worker/harbor-values.yaml, clusters/staging/worker/secrets/apps/harbor.yaml
ENH: Added backup to staging and credentials
---
Have you:
---
Have you:
=> Add backup and s3 creds

charts/dev/harbor/Chart.yaml, charts/staging/harbor/Chart.yaml
=> Bump version

charts/dev/harbor/Chart.yaml, charts/staging/harbor/Chart.yaml
Use latest harbor chart version
Blocked on: https://github.com/stfc/cloud-helm-charts/pull/66
---
Have you:
---
Have you:
=> Bump harbor chart version to 1.1.4

clusters/staging/worker/materials-galaxy-values.yaml
=> add internal-nginx annotation to galaxy ingress

charts/dev/argocd/Chart.yaml, charts/prod/argocd/Chart.yaml, charts/staging/argocd/Chart.yaml
Take 2 on promoting our version from dev (which has been running fine for a while) to staging and prod to get it to a known good version
Also bump dev (only) to latest argocd to let that start baking, so we can promote that later on too
---
Have you:
---
Have you:
=> Promote argocd again

clusters/prod/worker/rabbit-consumer-values.yaml
scale up rabbit consumer deployment from 1 to 3
=> scale up rabbit-consumers

clusters/staging/worker/apps.yaml, clusters/staging/worker/rabbit-consumer-values.yaml
We will be creating a secret for this so we need to deploy this first
---
Have you:
---
Have you:
=> DEP: Promote dev rabbit-consumer to staging

charts/staging/argocd/values.yaml
issue with syncing after upgrading argocd version
=> update argocd dependencies
