- prod-values/harbor-values.yaml
Related issue: https://stfc.atlassian.net/browse/CLDSCRM-592?atlOrigin=eyJpIjoiMWUzMDI3NTVkOWFkNGQ2ZDliYzc4NDVhYzAxYTMzOTYiLCJwIjoiaiJ9
Changes:
> Update harbor-values.yaml to not require SC

- clusters/david-harbor-test/app-values.yaml
- clusters/david-harbor-test/overrides/infra/deployment.yaml
- clusters/staging-management-cluster/infra-values.yaml
Creates a testing cluster to later test the deployment of Harbor
I've also had to resize the existing worker flavor to free up enough capacity on dev
As this is a deployment, we're trialling a different process for `deployment` labels:
- Single person review
- Infra does not need to be pre-tested
- IF: This only adds new infra, based on existing templates
> MAINT: Create a testing cluster for Harbor

- clusters/staging-management-cluster/infra-values.yaml
this cluster needs to be built using the development chart which is configured on a development branch
> point test cluster to use dev chart

- clusters/david-harbor-test/overrides/infra/deployment.yaml
Point over to prod infra, since Cinder dev keeps wobbling blocking us testing any deployments
> MAINT: david-harbor-test - Point to prod creds

- charts/argocd-infra/values.yaml
- charts/infra/capi/addons/monitoring.yaml
- charts/infra/capi/values.yaml
- clusters/anish-monitoring-test/app-values.yaml
- clusters/anish-monitoring-test/argocd-values.yaml
- clusters/anish-monitoring-test/overrides/infra/deployment.yaml
- docs/DEPLOYING_INFRA.md
Enable KubePrometheusStack Addon for CAPI and configure emailing config
Tested on my child cluster `anish-monitoring-test`
You may notice that `charts/infra/capi/addons/monitoring.yaml` and `clusters/anish-monitoring-test/infra/deployment.yaml` have very similar config - this is because we cannot get `cloud-deployed-infra` to pick up the new values file for capi `charts/infra/capi/addons/monitoring.yaml` without pushing that file to `main` branch. 
TLDR: when reviewing this PR ignore all files in `clusters/anish-monitoring-test/` as they will be deleted anyway
can't add a new file for capi as we are testing on a child cluster and cannot modify cloud-deployed-infra to point to our test branch so we have duplicated our monitoring config as cluster-specific config for our test cluster
> ENH: Enable Monitoring on CAPI

- clusters/david-harbor-test/overrides/infra/deployment.yaml
Label the nodes correctly so longhorn can use them
> BUG: Label nodes for longhorn values

- clusters/david-harbor-test/overrides/infra/deployment.yaml
Moves test harbor back to dev, now that the cinder issues have been resolved
> MAINT: Move test harbor back again

- .github/pull_request_template.md
---
Adds an initial PR template to the repository, to make a clear checklist and describe the two types of PR.
This should act as a nice reminder sheet, so we don't accidentally break prod in the future too.
---
Have you:
---
Have you:
> DOC: Add PR template to repo

- clusters/david-pr-test/app-values.yaml
- clusters/david-pr-test/overrides/infra/deployment.yaml
- clusters/staging-management-cluster/infra-values.yaml
Creates a cluster to test PR #33 so we can check the nodes are labelled by default
---
Have you:
---
Have you:
> DEPLOY: Create cluster to test node labels

- charts/argocd-apps/templates/cloud-deployed-apps.yaml
- charts/argocd-infra/templates/cloud-deployed-infra.yaml
- charts/infra/capi/values.yaml
- clusters/prod-mgmt/app-values.yaml
- clusters/prod-mgmt/argocd-values.yaml
- clusters/prod-mgmt/infra-values.yaml
- clusters/prod-mgmt/overrides/infra/deployment.yaml
Add prod management cluster and make it self-managing
Have you:
---
Have you:
> ENH: add prod-mgmt cluster

- charts/infra/capi/addons/monitoring.yaml
- clusters/staging-management-cluster/overrides/infra/deployment.yaml
- docs/DEPLOYING_INFRA.md
cluster name and environment needs to be set correctly so it points to staging-management-cluster
> MAINT: set cluster name for monitoring correctly

- clusters/prod-mgmt/overrides/infra/deployment.yaml
- clusters/staging-management-cluster/overrides/infra/deployment.yaml
- clusters/staging-worker/overrides/infra/deployment.yaml
- clusters/victoria-metrics-test/overrides/infra/deployment.yaml
- docs/DEPLOYING_INFRA.md
if the project has multiple external networks - cluster deployment fails - we need to explicitly define the "id" of the network we want to use for each cluster
**NOTE**: This will require us to re-make all of our clusters because this is a protected field and can't be changed on running clusters 
---
Have you:
---
Have you:
> BUG: explicitly define externalNetworkID

- charts/apps/longhorn/values.yaml
- charts/infra/capi/values.yaml
- docs/DEPLOYING_APPS.md
Added a default node label to make nodes longhorn stores 
Changed docs to reflect this
---
Have you:
---
Have you:
> Changed default node labels

- clusters/prod-mgmt/infra-values.yaml
updating prod to point to updated commit/tag which fixes external network id
> make prod-mgmt use prod tag for tracking

- clusters/prod-mgmt/app-values.yaml
- clusters/prod-mgmt/infra-values.yaml
- clusters/victoria-metrics-prod/app-values.yaml
since this is a prod-change we are going to need to create a tag prod-v1.0.1-vm as soon as this is merged 
---
Have you:
---
Have you:
> ENH: make prod-mgmt manage a new VM prod cluster

- clusters/prod-mgmt/app-values.yaml
- clusters/prod-mgmt/infra-values.yaml
- clusters/victoria-metrics-prod/app-values.yaml
commit SHAs don't work - we'll go back to the original - we'll make a prod tag on the latest commit and deploy it off of that - we lose CI - and need to manually run deploy for now
> make prod clusters follow prod tag

- clusters/jupyter-training/app-values.yaml
- clusters/jupyter-training/overrides/infra/deployment.yaml
- clusters/prod-mgmt/infra-values.yaml
Adds the cluster infra for our training Jupyterhub, this will just manage the infra since we haven't tested deploying JHub via argo yet unlike the infra which is well-tested at this point
---
Have you:
---
Have you:
> DEPLOY: Add training Jupyterhub on prod

- clusters/jupyter-training/overrides/infra/deployment.yaml
This PR changes the number of GPUs in each node group.
---
Have you:
---
Have you:
> MAINT: Change size of GPU nodegroups

- charts/infra/capi/addons/monitoring.yaml
monitoring intervals were close together and spamming our ticketing system - alertmanager sending multiple tickets for the same issue should not be a problem anymore
> BUG: fix monitoring intervals

- clusters/prod-mgmt/overrides/infra/deployment.yaml
- clusters/prod-worker/overrides/infra/deployment.yaml
- clusters/staging-management-cluster/overrides/infra/deployment.yaml
- clusters/staging-worker/overrides/infra/deployment.yaml
- clusters/victoria-metrics-test/overrides/infra/deployment.yaml
- clusters/vm-prod/overrides/infra/deployment.yaml
- docs/DEPLOYING_INFRA.md
There should only be a single network called External. The UUID approach was a hang-over from the fact dev-openstack had a superflous network created within the project.
Revert this back to use the External network everywhere by default.
Note: Since prod is pinned to a tag, this will not impact us until we move the tag forward. Where we will need to re-deploy pointing to the External network. This is a downside of specifying the UUID of the net
---
Have you:
--- …
> MAINT: Drop network UUIDs

- clusters/staging-worker/overrides/infra/deployment.yaml
setup monitoring and use updated floating ip for ingress as the previous floating ip doesn't seem to exist anymore
---
Have you:
---
Have you:
> MAINT: setup monitoring on staging-worker

- clusters/david-pr-test/app-values.yaml
- clusters/david-pr-test/overrides/infra/deployment.yaml
- clusters/staging-management-cluster/infra-values.yaml
This was used as a deployment target for various PRs including cert bot. Now they've been merge drop the cluster from our list of staging infra targets.
---
Have you:
---
Have you:
> DEPLOY: Remove infra from testing PR

- charts/infra/capi/addons/monitoring.yaml
- clusters/jupyter-training/overrides/infra/deployment.yaml
- clusters/prod-mgmt/overrides/infra/deployment.yaml
- clusters/prod-worker/overrides/infra/deployment.yaml
- clusters/staging-management-cluster/overrides/infra/deployment.yaml
- clusters/staging-worker/overrides/infra/deployment.yaml
Now that we have cert-manager as a dependency chart - we should use its self-signed cert capabilities for setting up tls for monitoring stack.
For clusters which have already been setup with manual tls certs - override the annotation for setting up self-signed cert using cert-manager
To test this - I want to deploy this to staging and see if vm-stage no longer complains about missing certs
> MAINT: use cert-manager for self-signed certs for Monitoring

- clusters/test-capi-addons-2/infra-values.yaml
- clusters/test-capi-addons-2/overrides/infra/deployment.yaml
Update credential name and add cluster to list of infra in infra values file 
---
Have you:
---
Have you:
> Update credential name and update infra value

- charts/infra/capi/networking.yaml
This is a bug and needs to be removed since its looking for an ID and not a name
This shouldn't have any affect on clusters already made
> MAINT: remove setting cluster networking

- charts/argocd/Chart.yaml
Update to use the latest ArgoCD helm chart
---
Have you:
---
Have you:
> MAINT: Bump argo-cd helm version to 6.10.2

- docs/child-clusters.md
- docs/clusters.md
Some updates to the documentation for deploying clusters. Main change is to split the two deployment options into separate pages and some reformatting.
---
Have you:
---
Have you:
> DOC: Update docs on deploying clusters

- clusters/dev/management/apps.yaml
The template is unable to preserve an application, since it's defined in
the applicationset instead of an application set creating N applications.
This means you can't add preserve to the template, since theres no way for Argo to actually do this
This should fix the auto-sync on dev failing to reconcile currently
- See second commit for human diff, the first is auto-formatting
---
Have you:
---
Have you:
> Fix appset invalid preserve

- README.md
- docs/README.md
- docs/app-setup.md
- docs/child-clusters.md
- docs/clusters.md
- docs/deploying-apps.md
- docs/infra-setup.md
Updates to some of the formatting and layout of documentation
---
Have you:
---
Have you:
> DOC: Reformatting of documentation

- clusters/staging/management/apps.yaml
- secrets/staging/management/.sops.yaml
- secrets/staging/management/api-server-fip.yaml
- secrets/staging/management/app-creds.yaml
- Rotates the app creds and FIP so it goes into the proper project instead of Megan's scratch space
- Rotate the Argo keys ready for deployment
---
Have you:
---
Have you:
> Staging deployment

- secrets/staging/management/app-creds.yaml
The previous commit updated the app cred secret, but did not rotate the public key for the app creds. This is preventing us from actually deploying.
---
Have you:
---
Have you:
> Rotate the key on app-creds too

- clusters/staging/management/apps.yaml
Use the app name implicitly, rather than explicitly saying the name again for the helm release: https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm-release-name
This ensures that the cluster name matches the user's expectation when it's installed
---
Have you:
---
Have you:
> BUG: Use app name implicitly

- charts/dev/openstack-cluster/requirements.yaml
> bump capi-helm-chart version on dev chart

- secrets/dev/worker/.sops.yaml
this should be the same as management argo key because management needs to decrypt these secrets as it is responsible for building all worker clusters
> BUG: rotate worker sops key

- charts/dev/cluster-api-addon-provider/requirements.yaml
release 0.6.0 hasn't yet been released to chart repo
> change back capi-addons version to 0.5.9

- charts/staging/cert-manager/values.yaml
this doesn't work for child clusters - the values were misconfigured
> BUG: install crds for cert-manager

- docs/clusters.md
bug with name mismatching - explicitly state to create clusters `<env>-<cluster-type>-cluster` before applying argo deploy.sh
> DOC: update docs

- charts/dev/capi-infra/values.yaml
- clusters/dev/management/infra-values.yaml
- clusters/dev/worker/infra-values.yaml
We had to turn off storage since cinder is broken on dev. 
We've disabled sending alerts for this cluster
Places shared config for monitoring in chart values ready for promotion
> PROTOTYPE: Enable monitoring on dev

- clusters/dev/galaxy/infra-values.yaml
this is running on prod openstack so we don't have the new image available
> hotfix - revert galaxy cluster image to 1.28.7

- clusters/dev/management/apps.yaml
- secrets/dev/.sops.yaml
- secrets/dev/smtp-smarthost.yaml
this will set the smtp smarthost endpoint as a secret for dev - this is empty because we don't want to send alerts for dev - but makes it easier to promote changes to staging and prod
> MAINT: setup smtp smarthost secret for dev

- charts/dev/capi-infra/values.yaml
dev capi-infra values previously were set to not use cinder volumes because they were broken - this should have been put into cluster-specific values rather than the shared chart values - this PR fixes that
In addition, I forgot to specify to use cloud-support email for sending alerts
> BUG: make dev capi-infra values consistent with staging

- clusters/dev/management/infra-values.yaml
this is the only dev cluster we should add alerting to - just to ensure that we can create new clusters for development work
> ENH: Add alerting to dev management

- charts/dev/capi-infra/values.yaml
- charts/staging/capi-infra/values.yaml
I thought we removed prometheusSpec (dev specific value) from capi-infra charts but apparently not
> BUG: make capi-infra chart consistent

- charts/dev/capi-infra/values.yaml
- clusters/dev/galaxy/infra-values.yaml
- clusters/dev/management/infra-values.yaml
- clusters/dev/worker/infra-values.yaml
An attempt to fix an issue where labels don't get applied to every alert leaving the alert having blank values for env and cluster which leads to confusing alert messages
> BUG: rule labels don't get applied to every prometheus alert

- charts/dev/capi-infra/values.yaml
- clusters/dev/galaxy/infra-values.yaml
- clusters/dev/management/infra-values.yaml
- clusters/dev/worker/infra-values.yaml
related to #161 - that fix doesn't work 
Instead we'll try using external rule labels for prometheus to bypass the need to set label for each rule individually - this circumvents the issue found in azimuth-cloud capi-helm charts where they hardcode creating prometheus rules without a way for us to add in these labels - https://github.com/azimuth-cloud/capi-helm-charts/blob/4207923e8167fce27a5b96712cd164be3a5023d5/charts/cluster-addons/templates/ingress-nginx.yaml#L89-L121
More on externalrules can be found here - https://support.tools/use-external-labels-prometheus-alerts/
> BUG: set external rule labels

- charts/dev/capi-infra/values.yaml
make the subject line a little bit more informative for alerts - specify the service in question - and then what alerts get fired. If there's no specified "alertname" - then it can be assumed that multiple alerts have fired
> BUG: set a subject for alerts

- charts/staging/cert-manager/values.yaml
InstallCRDs flag is deprecated - use `crds.enable and crds.keep` instead
---
Have you:
---
Have you:
> BUG: use crds.enable=true

- clusters/dev/vicmet/infra-values.yaml
- secrets/dev/vicmet/api-server-fip.yaml
- secrets/dev/vicmet/app-creds.yaml
Change app-creds and FIPs back to dev 
---
Have you:
---
Have you:
> Move vicdev cluster back to dev

- clusters/dev/worker/infra-values.yaml
This image is not usable due until new version of capi helm charts is released
> BUG: use older image for dev worker

- clusters/dev/vicmet/infra-values.yaml
set boilerplate monitoring config on vicmet cluster in the hopes that it solves the issues with ingress
> MAINT: enable monitoring on vicmet cluster

- clusters/dev/galaxy/infra-values.yaml
enable alerting on dev galaxy - so we can respond to issues as we trial users on it
> MAINT: enable alerts on dev galaxy

- clusters/dev/galaxy/apps.yaml
there's a bug with galaxy with argocd where duplicate setup jobs keep getting instantiated - looking to disable galaxy and test manually deploying galaxy to rule out if this is an application issue
Also deleting capi-addon-provider - this is a child cluster so I don't think its necessary
> BUG: disable galaxy

- charts/dev/capi-infra/values.yaml
Simplify alertmanager routing - we only need one route - for emailing.
Just Inhibit the watchdog and infoinhibitor alerts so they don't send notifications
add a time range where emails are active - during office hours
> MAINT: simplify alertmanager routing

- secrets/prod/management/.sops.yaml
- secrets/prod/management/api-server-fip.yaml
- secrets/prod/management/app-creds.yaml
Recreating the prod management cluster
Original private key no longer owned
---
Have you:
---
Have you:
> [Deployment] Rotate prod management keys

- clusters/prod/management/infra-values.yaml
- clusters/prod/worker/infra-values.yaml
Updates the ingress IPs to reflect the wildcard DNS entry Switch the existing services to start using the wildcard subdomains
---
Have you:
---
Have you:
> Update ingress IPs and DNS entries for prod clusters

- secrets/staging/worker/api-server-fip.yaml
This was using the same FIP as the prod ingress, causing the two to fight. Allocate a new kubeAPI FIP and point to that
---
Have you:
---
Have you:
> BUG: Point staging worker to another kubeapi FIP

- charts/dev/argocd/Chart.yaml
- charts/staging/argocd/Chart.yaml
- charts/staging/argocd/requirements.yaml
AppSets are not currently re-generating clusters with any env name in their path (e.g. staging) due to an ArgoCD bug. This was fixed in September so pull the latest image onto staging to see if this fixes the problem
Bumps the version on dev
Pulls the version straight through to staging to test the bug-fix on the affect env
---
Have you:
---
Have you:
> Pull latest version of ArgoCD for AppSet bug fix

- charts/prod/argocd/Chart.yaml
- charts/prod/argocd/requirements.yaml
This promotes argocd to prod after being deployed on staging where it resolved the problem with staging-worker not being deployed
---
Have you:
---
Have you:
> MAINT: Promote latest argocd to prod

- charts/prod/capi-infra/requirements.yaml
- charts/prod/cluster-api-addon-provider/requirements.yaml
- clusters/dev/management/infra-values.yaml
- clusters/staging/management/infra-values.yaml
- Fix the requirements.yaml getting pulled in instead of chart.yaml on prod the KCP to fail to update with an older chart
- Don't override the defaults across our management clusters, use the safest option which is in the chart defaults as these are the hardest to recover
---
Have you:
---
Have you:
> Misc fixes across deployed clusters

- charts/dev/capi-infra/Chart.yaml
- charts/dev/capi-infra/values.yaml
Bumps the CAPI image and version on dev in prep for rollout to staging and prod next week
---
Have you:
---
Have you:
> MAINT: Bump CAPI image and version on dev

- clusters/staging/worker/infra-values.yaml
Allow autoscaler rules for manila-csi to work
Increase worker nodes on the staging worker cluster to allow autoscaler rules for manila-csi to work
Anti-affinity rules blocking the scaler from creating 3 replicas on 2 nodes
---
Have you:
---
Have you:
> [DEPLOYMENT] Scale up worker nodes

- clusters/dev/rwhiting/apps.yaml
- clusters/dev/rwhiting/argocd-setup-values.yaml
- clusters/dev/rwhiting/infra-values.yaml
- secrets/dev/rwhiting/.sops.yaml
- secrets/dev/rwhiting/api-server-fip.yaml
- secrets/dev/rwhiting/app-cred.yaml
> DEPLOY: Deploying test cluster for Longhorn issue.

- clusters/dev/worker/materials-galaxy-values.yaml
Galaxy redirect after oidc needs to match the new url galaxy.dev-worker.* rather than galaxy.dev.*
> BUG: set proper redirect url

- charts/prod/manila-csi/Chart.yaml
- charts/prod/manila-csi/templates/manila-sc.yaml
- charts/prod/manila-csi/values.yaml
- charts/prod/victoria-metrics/Chart.yaml
- charts/prod/victoria-metrics/values.yaml
- clusters/prod/worker/apps.yaml
- clusters/prod/worker/argocd-setup-values.yaml
- clusters/prod/worker/infra-values.yaml
- clusters/prod/worker/vicmet-values.yaml
Copied app charts from staging to prod
Created new cluster files comparable to staging, changed to point to prod values
Creating a running prod version of Victoria-Metrics
---
Have you:
---
Have you:
> Promotion of victoria metrics, Staging -> Prod

- clusters/dev/management/apps.yaml
- clusters/dev/worker/apps.yaml
now feature branch update-secrets is merged we can re-point dev clusters to main
> MAINT: point dev worker and mgmt to main

- charts/dev/capi-infra/values.yaml
workaround for default group_by=[...] that azimuth adds
https://github.com/azimuth-cloud/capi-helm-charts/blob/main/charts/cluster-addons/templates/monitoring/kube-prometheus-stack.yaml#L41-L44
this means that alert-manager cluster addon forces no grouping by default on the top route  - which can't be overridden
adding "null" as the top route that doesn't have a receiver hopefully means that all alerts get forwarded to child route - which will group by service and cluster - so all alerts related to a service get sent in one email notification - it needs testing
> BUG: modify the group interval and add null reciever

- clusters/dev/vicmet/apps.yaml
leftover from using feature-branch that has been merged
> BUG: make vicmet cluster follow main

- clusters/staging/worker/infra-values.yaml
this wasn't turned on so longhorn was failing to spin up on staging worker
> BUG: add nodelabels for enabling longhorn storage

- charts/dev/chatops/secrets-templates/secrets.yaml
- charts/dev/chatops/templates/cloud-chatops.yaml
- charts/dev/chatops/templates/config-map.yaml
- charts/dev/chatops/templates/secrets.yaml
- charts/dev/chatops/values.yaml
- secrets/dev/worker/apps/chatops.yaml
Includes Helm Templating bug fixes for ChatOps deployment. Also, changes container image from a dev image to a production image
---
Have you:
---
Have you:
> BUG: Fix helm templating for ChatOps deployment

- charts/dev/capi-infra/Chart.yaml
- charts/dev/capi-infra/values.yaml
- charts/dev/cluster-api-addon-provider/Chart.yaml
only affects dev
Bump capi-infra chart to 0.12.2
bump capi-addon provider to 0.7.2
bump dev clusters to use 1.30.8 k8s image
> Bump capi-infra chart to 0.12.2

- clusters/dev/cloud-chatops/apps.yaml
- clusters/dev/cloud-chatops/argocd-setup-values.yaml
- clusters/dev/cloud-chatops/infra-values.yaml
Editing setup values from original PR to setup apps. The values paths were not changes from worker to cloud-chatops cluster.
Also, adding set up values for argocd domain to access the UI
---
Have you:
---
Have you:
> Edit chatops setup values

- clusters/dev/cloud-chatops/apps.yaml
Moving ChatOps App of Apps to feature branch. Missed this in the previous PR.
---
Have you:
---
Have you:
> MAINT: Move cluster App of Apps to feature branch

- charts/dev/chatops/values.yaml
- secrets/dev/cloud-chatops/apps/chatops.yaml
Updating ChatOps to 5.0.1 to fix a bug with `/prs mine`.
Updating the Authentication tokens as they were regenerated.
Adding other cloud members to the config map
---
Have you:
---
Have you:
> Dev cloud chatops

- clusters/dev/management/infra-values.yaml
- clusters/dev/worker/infra-values.yaml
- clusters/staging/management/infra-values.yaml
- clusters/staging/worker/infra-values.yaml
BlackBox Probe Exporter is used just to check API endpoints and certificate expiry - this is not necessary for dev/staging as we have other methods of alerting on this. I'm disabling them completely and keeping it just on prod (this prevents 3 sets of the same alert being sent)
> Disable API Down/Certificate Expiry alerts on dev/staging

- charts/dev/chatops/Chart.yaml
- charts/dev/chatops/values.yaml
- charts/staging/chatops/Chart.yaml
- charts/staging/chatops/secrets-templates/secrets.yaml
- charts/staging/chatops/templates/cloud-chatops.yaml
- charts/staging/chatops/templates/config-map.yaml
- charts/staging/chatops/templates/secrets.yaml
- charts/staging/chatops/values.yaml
- clusters/dev/cloud-chatops/apps.yaml
- clusters/dev/cloud-chatops/chatops-values.yaml
- clusters/staging/worker/apps.yaml
- clusters/staging/worker/chatops-values.yaml
- secrets/dev/cloud-chatops/apps/chatops.yaml
- secrets/staging/worker/apps/chatops.yaml
Taking down the ChatOps app on dev. Changing replicas to 0 and changing image tag to be placeholder for next dev changes.
Also, changing dev secrets to use the Dev Slack App rather than production which is being promoted.
**Promoting** chatops app on dev chatops cluster to staging worker cluster.
---
Have you:
---
Have you:
> Promote chatops to staging

- charts/dev/longhorn/values.yaml
Longhorn settings were not being applied due to invalid values for some settings longhorn#6815
Update values to match allowed values found here: https://github.com/longhorn/charts/blob/v1.8.x/charts/longhorn/questions.yaml
Set drain policy to "block-for-eviction" to automatically evict replicas from draining nodes: https://longhorn.io/docs/1.7.2/maintenance/maintenance/#node-drain-policy-recommendations
---
Have you:
---
Have you:
> Bug: Fix longhorn settings

- charts/dev/capi-infra/values.yaml
fully create upgraded worker node before deleting old one. Allows things like longhorn volumes to migrate better
> change rollout strategy to avoid deleting worker nodes

- charts/staging/capi-infra/Chart.yaml
- charts/staging/capi-infra/values.yaml
- charts/staging/longhorn/Chart.yaml
- charts/staging/longhorn/requirements.yaml
- charts/staging/longhorn/values.yaml
- clusters/dev/worker/infra-values.yaml
- clusters/staging/management/infra-values.yaml
- clusters/staging/worker/infra-values.yaml
promote all dev changes to capi-infra chart to staging
- image changes
- bump capi-helm-chart to 0.12.2
- a few dns changes to match what's expected
- a few prometheus/alertmanager tweaks
> Promote dev capi changes to staging

- charts/staging/capi-infra/values.yaml
bump CAPI images which have been patched to mitigate rsync CVE
> bump CAPI images on staging

- secrets/dev/cloud-chatops/infra/app-creds.yaml
encase secret values in `openstack-cluster` as the config belongs to the dependency chart
> BUG: fix app-cred for chatops cluster

- secrets/staging/worker/apps/chatops.yaml
Adding more cloud members to the values so their names are updated in the messages.
---
Have you:
---
Have you:
> ENH: Add more cloud members to the values

- charts/dev/manila-csi/templates/manila-secret.yaml
- charts/dev/victoria-metrics/values.yaml
- clusters/dev/vicmet/apps.yaml
- secrets/dev/vicmet/apps/.sops.yaml
- secrets/dev/vicmet/apps/manila-secret.yaml
Added config for the vmbackup sidecontainer to run alongside the vmstorage pod
vmbackup will be interactable from kubectl 
---
Have you:
---
Have you:
> [ENH] vmbackup config

- charts/prod/rabbit-consumers/Chart.yaml
- clusters/dev/worker/apps.yaml
- clusters/dev/worker/rabbit-consumer-values.yaml
- clusters/prod/worker/apps.yaml
- clusters/prod/worker/rabbit-consumer-values.yaml
point to new rabbitmq node hv748
make prod worker run rabbit consumers
waiting on secrets to be added to dev worker before spinning up rabbit on dev
> setup rabbit-consumers on argocd

- charts/staging/victoria-metrics/values.yaml
Promotion of victoria metrics changes to add vmbackup sidecar 
---
Have you:
---
Have you:
> Promote victoria metrics chart to staging

- charts/dev/cert-manager/Chart.yaml
- charts/dev/opensearch/secret-templates/opensearch.yaml
- charts/staging/cert-manager/Chart.yaml
- charts/staging/cert-manager/requirements.yaml
- charts/staging/cert-manager/values.yaml
- charts/staging/chatops/values.yaml
- charts/staging/cluster-api-addon-provider/Chart.yaml
- charts/staging/cluster-api-addon-provider/requirements.yaml
- charts/staging/opensearch/Chart.yaml
- charts/staging/opensearch/secret-templates/opensearch.yaml
- charts/staging/opensearch/templates/admin-secret.yaml
- charts/staging/opensearch/templates/longhorn-storageclass.yaml
- charts/staging/opensearch/templates/opensearch-cluster.yaml
- charts/staging/opensearch/templates/opensearch-dashboards-ingress.yaml
- charts/staging/opensearch/templates/opensearch-nodes-ingress.yaml
- charts/staging/opensearch/templates/security-config-secret.yaml
- charts/staging/opensearch/values.yaml
- clusters/staging/worker/chatops-values.yaml
- add opensearch chart to staging
- bump cert-manager to 1.15.3
- fix inconsistency with chatops values - `env` needs to be a cluster-specific value
This PR does not affect infrastructure charts like capi/capi-addons. See PR #272
> bump dev charts to staging

- .github/workflows/promote_to_prod.yaml
- .github/workflows/promote_to_staging.yaml
will automatically promote setup a PR to promote charts from dev-staging and staging-prod
---
Have you:
---
Have you:
> add github actions to setup automated promotion of charts

- .github/workflows/promote_to_staging.yaml
dev is volatile and we shouldn't promote from dev to staging on a schedule, instead it should only be manually triggered
> don't promote from dev

- secrets/staging/worker/apps/chatops.yaml
Updating the GitHub PAT for chatops as it expired.
Have you:
---
Have you:
> MAINT: Update GitHub token

- clusters/dev/management/apps.yaml
smtp smarthost secret is shared between all environments
> BUG: fix issue with pathing to shared secret

- charts/dev/materials-galaxy/Chart.yaml
- clusters/dev/worker/materials-galaxy-values.yaml
- clusters/dev/worker/secrets/apps/materials-galaxy.yaml
use git-sync to manage latest local versions of repos containing galaxy tools.
Now a simple restart of the galaxy web container is all that's needed to pick up changes from various repos
Moved repo configuration here because that's likely going to need to be changed consistently
deploy's changed made in this PR - https://github.com/stfc/cloud-helm-charts/pull/15
> use alpha chart for materials-galaxy

- charts/dev/argocd/Chart.yaml
tested and working
- will require a rebuild of dev worker and management clusters by removing argo namespae and running `./deploy.sh` again - should not disrupt any other services
> bump argo major version 7.8.0 - 8.0.2

- clusters/staging/worker/apps.yaml
issue with galaxy postgresql label being too big solved with argocd serversideapply=true
> bug: set staging app-of-apps serversideapply=true

- charts/dev/argocd/values.yaml
- charts/dev/harbor/Chart.yaml
- charts/staging/argocd/values.yaml
- charts/staging/harbor/Chart.yaml
- clusters/staging/worker/argocd-setup-values.yaml
- clusters/staging/worker/harbor-values.yaml
- clusters/staging/worker/infra-values.yaml
- clusters/staging/worker/materials-galaxy-values.yaml
- clusters/staging/worker/vicmet-values.yaml
Rename default ingressclass to internal-nginx
Point other services to use internal-nginx
Create 2nd ingressclass for harbor
Update staging harbor url and floating ip
---
Have you:
---
Have you:
> Set up harbor specific ingress for staging

- clusters/dev/management/apps.yaml
- clusters/dev/management/infra-values.yaml
- clusters/dev/management/secrets/infra/basic-auth.yaml
- clusters/dev/worker/infra-values.yaml
- clusters/dev/worker/secrets/infra/basic-auth.yaml
- clusters/staging/management/apps.yaml
- clusters/staging/management/infra-values.yaml
- clusters/staging/management/secrets/infra/basic-auth.yaml
- clusters/staging/worker/infra-values.yaml
- clusters/staging/worker/secrets/infra/basic-auth.yaml
Setting up basic auth on the monitoring endpoints (prometheus, alertmanager and grafana) for dev and statging
---
Have you:
---
Have you:
> Monitoring basic auth

- charts/dev/capi-infra/Chart.yaml
- charts/dev/longhorn/Chart.yaml
- charts/dev/materials-galaxy/Chart.yaml
Bump dependency chart versions on dev
---
Have you:
---
Have you:
> MAINT: Bump chart dependencies on dev

- clusters/prod/management/infra-values.yaml
- clusters/prod/worker/infra-values.yaml
- clusters/staging/management/infra-values.yaml
See each commit for more details
- Set the machine count for each cluster to sensible values based on current usage
- Switch workers for prod to use dep-l2, the same as staging, as our workloads can handle the additional risk and it keeps more space in the non-dep l3 pool
---
Have you:
We can come back in and increase/decrease these values later on too.
---
Have you:
> Flavor and count tweaks for staging and prod

- .github/workflows/check_helm_updates.yaml
- .github/workflows/pr_copied_files.yaml
- .github/workflows/update_charts.sh
staging charts will now be updated periodically to the latest chart advertised on cloud-helm-charts
removed the check for testing if dev matches staging because dev is likely to always be in flux. This github action ensures that our latest released charts will always be running on staging
> add github action to update helm dependencies

- clusters/dev/management/infra-values.yaml
- clusters/dev/worker/infra-values.yaml
- clusters/prod/worker/infra-values.yaml
- clusters/staging/management/infra-values.yaml
- clusters/staging/worker/infra-values.yaml
don't need every staging/dev cluster sending info on openstack networking issues - typo when setting enabled: false
> BUG: turn off blackbox exporters on non-prod clusters

- clusters/_shared/monitoring.yaml
- clusters/staging/management/infra-values.yaml
- clusters/staging/worker/infra-values.yaml
we've got other alerting which tells us when openstack.stfc.ac.uk and the APIs are having issues.
We don't need tickets from every prod cluster telling us this, and they are not tuned correctly so they keep spamming the ticket queue.
So we should turn it off globally
> silence blackbox probe alerts globally
